### ISSUE TITLE
Multiple timeouts for shell-integration

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#123]
Instead of only using the default(per config) backend and one timeout, the shell-integration could support various timeouts with different backends each. For example, local notification if longer than 5 seconds, push notification if longer than a minute.

Config idea:
```yaml
shell-integration:
  - timeout: 5
    backend: default
  - timeout: 60
    backend: pushover
```

makes the toplevel `shell-integration` key special (like `backend` and `backends`)
Should consider sections? see #TBD for more ideas.
