### ISSUE TITLE
Reorganized config? Breaking change - 3.0?

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#124]
Adding the `shell-integration` in #123 top level key adds to the confusion of reserved keywords at the top level of the config. Additionally, it'd be neat if different sub-commands could have different default backends. For example `ntfy shell-integration` could use local notifications and `nfty done` could use push notifications.

Rough idea...
```yaml
default-backends:
  done: pushover
  shell-integration: default
shell-integration:
  - timeout: 5
    backend: default
  - timeout: 60
    backend: pushover
backends:
  pushover:
    user_key: hunter2
```
