### ISSUE TITLE
Suspending creates permanent notification pop up (linux backend)

### ISSUE THREAD

**Issue by rcywongaa** [dschep/ntfy#210]
### Configs
`ntfy.yml`
```
backends:
    - linux
linux:
    urgency: low
    transient: true
    timeout: 5
```

`.zshrc`
```
eval "$(ntfy shell-integration)"
```

### Steps to reproduce
1. Run `sleep 30`
1. After 10s, hit Ctrl Z to send the sleep process to background
1. Notification pop up appears with message: 
   > sleep 15" failed (code 148) in 0:11 minutes
1. Pop up never disappears

The same thing happens when suspending any application that has run for more than 10s
