### ISSUE TITLE
xmpp config?

### ISSUE THREAD

**Issue by jungle-boogie** [dschep/ntfy#25]
Hello,

I've instaledl 'ntfy[xmpp]' but I don't know what the yml file needs to look like and how I connect it to a xmpp server. Do you have any documentation that can be shared so I can set it up?

Thanks,
sean

**Comment by dschep** [comment]
Hey @danryder, think you could jump in here?

**Comment by danryder** [comment]
This isn't formal documentation, but most of this is present in comments in
the xmpp backend code.

Here's what you'll need for google hangouts via xmpp backend, assuming you
have dnspython installed.  It's really the only XMPP target I've tried so
far...

Set up an "application password" in your Google Accout Settings & paste it
below

    "xmpp": {"jid": "$USERNAME@gmail.com",
             "password": "$PASSWORD",
             "mtype":"chat",
             "recipient": "TARGETUSERNAME@gmail.com"}

If you want to send a chat to another user instead, use "-o recipient
OTHERTARGET@gmail.com"

If you don't have dnspython installed, you'll also need to pass in
'hostname' of 'talk.google.com'

Hope this helps

**Comment by jungle-boogie** [comment]
Jitsi offers free xmpp accounts:
https://jitsi.org/index.php/Register/Register

Do you think there would be any reason it wouldn't work?

**Comment by danryder** [comment]
nothing comes to mind

feel free to experiment though, curious what you find out

**Comment by jungle-boogie** [comment]
Final question,

with the stanza above, will this go in the .ntfy.yml file with the `backend` being xmpp and the configuration of what's above?

Thanks and I'll let you know about jitsi.

**Comment by dschep** [comment]
Yup, in prettier & complete YAML version of @danryder's example config
```
---
backends:
    - xmpp
 xmpp
    - jid: "$USERNAME@gmail.com"
    - password: "$PASSWORD"
    - mtype: "chat"
    - recipient: "TARGETUSERNAME@gmail.com
```

**Comment by danryder** [comment]
Yep you got it

**Comment by dschep** [comment]
Oops. just noticed `xmpp` should've been `xmpp:` in my YAML version. Updated.

**Comment by jungle-boogie** [comment]
My yml file:

```
---
backends:
        - pushover
        - xmpp  
pushover:
        user_key: 2600
xmpp:
        - jid: "jungle-boogie@jit.si"
        - password: "xxxxxxxxxx"
        - mtype: "chat"
        - recipient: "jungle-boogie@jit.si"
```

Test:
```
ntfy done sleep 1                                     
Traceback (most recent call last):
  File "/usr/local/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/ntfy/cli.py", line 121, in main
    return notify(message, args.title, config, **dict(args.option))
  File "/usr/local/lib/python3.4/site-packages/ntfy/__init__.py", line 29, in notify
    backend_config.update(kwargs)
AttributeError: 'list' object has no attribute 'update'
```

pushover does work and I get the alert.

**Comment by dschep** [comment]
Ah. Oops. I didn't make that yml file correctly. xmpp should contain a dict, not a list of dicts (the `- ` before `jid: ` and such shouldn't be there. Here's the right formt:
```
---
backends:
        - pushover
        - xmpp  
pushover:
        user_key: 2600
xmpp:
        jid: "jungle-boogie@jit.si"
        password: "xxxxxxxxxx"
        mtype: "chat"
        recipient: "jungle-boogie@jit.si"
```
