### ISSUE TITLE
Move AUTO_NTFY_DONE_IGNORE config to the yaml file

### ISSUE THREAD

**Issue by funkyfisch** [dschep/ntfy#273]
This could be an easy way to enable better parametric filtering of commands + subcommands.

For example I might not want to have a notification for git commit (because git commit might take more than 10 s while im editing using my editor) but I still want to time git pull in case im working with a huge repo

This could look something like

```yaml
backends:
  # ...
auto_ignore_cmds:
  - git:
      - commit
  - chezmoi:
      - edit
```
