### ISSUE TITLE
Multiple configs for the same backend type (e.g. 2 XMPP configs)

### ISSUE THREAD

**Issue by dschep** [dschep/ntfy#30]
It'd make sense to allow multiple configurations for the same backend type in your config file. I propose doing this by adding a special `backend` parameter to options that is used instead of the name listed in the `backends` option and the backend's top level key. For example, to have a configs that send to different devices in pushover:

```
---
backends:
    - pushover
pushover:
    user_key: t0k3n
cell:
    user_key: t0k3n
    device: nexus5x
    backend: pushover
```

Then `ntfy send foobar` would send a notification to all your pushover devices, where as `ntfy -b cell send foobar` would only go to the device named `nexus5x` using pushover.

cc @danryder
